---
- name: Run rhc connect command
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Execute rhc connect command
      ansible.builtin.command: "rhc disconnect"
      no_log: true
